name: PHP Composer

on:
  push:
  schedule:
    # Run every Saturday at 5 am
    - cron: 0 5 * * 6
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-versions }} without code coverage
      if: matrix.php-versions != '7.4'
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
    - name: Setup PHP ${{ matrix.php-versions }} with code coverage
      if: matrix.php-versions == '7.4'
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Setup Problem Matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
        echo "::set-output name=date::$(date "+%m")"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.composer-cache.outputs.date }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ steps.composer-cache.outputs.date }}-
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check code style
      run: composer run-script phpcs

    - name: Run tests
      run: composer run-script phpunit

    # Ensure the next test run fetches the latest test ruleset.
    - name: Remove httpwg/structured-header-tests from composer cache
      run: rm -rf $(composer config cache-files-dir)/httpwg

    - name: Upload code coverage report
      if: matrix.php-versions == '7.4'
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: tmp/code-coverage

    - name: Upload code coverage to codecov
      if: matrix.php-versions == '7.4'
      uses: codecov/codecov-action@v1
      with:
        file: ./tmp/code-coverage/clover.xml
        flags: phpunit
