name: PHP Composer

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Setup Problem Matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check code style
      run: composer run-script phpcs

    - name: Run tests
      run: composer run-script phpunit

    # Ensure the next test run fetches the latest test ruleset.
    - name: Remove httpwg/structured-header-tests from composer cache
      run: rm -rf $(composer config cache-files-dir)/httpwg
